# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-28 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import policy.models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Policy',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, verbose_name='策略名称')),
                ('item', policy.models.ListField(default=[])),
                ('memo', models.CharField(blank=True, max_length=255, null=True, verbose_name='备注')),
                ('creator', models.CharField(blank=True, max_length=16, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('deleted_time', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': '策略',
                'verbose_name_plural': '策略',
                'db_table': 'policy',
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='PolicySet',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255)),
                ('memo', models.CharField(blank=True, max_length=255, null=True)),
                ('creator', models.CharField(blank=True, max_length=16, null=True)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('deleted_time', models.DateTimeField(null=True)),
            ],
            options={
                'verbose_name': '策略集',
                'verbose_name_plural': '策略集',
                'db_table': 'policyset',
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='PolicySetRelation',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('execute_date', models.DateField()),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True, null=True)),
                ('updated_time', models.DateTimeField(auto_now=True, null=True)),
                ('deleted_time', models.DateTimeField(null=True)),
                ('policy', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_relations', to='policy.Policy')),
                ('policyset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policyset_relations', to='policy.PolicySet')),
            ],
            options={
                'verbose_name': '策略集映射',
                'verbose_name_plural': '策略集映射',
                'db_table': 'policyset_relation',
                'ordering': ('execute_date',),
            },
        ),
        migrations.CreateModel(
            name='PolicySetSendDown',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('group_id', models.CharField(max_length=16)),
                ('is_deleted', models.BooleanField(default=False)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('updated_time', models.DateTimeField(auto_now=True)),
                ('deleted_time', models.DateTimeField(null=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_send_down_policysets', to='hub.Hub')),
                ('policyset', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policyset_send_down_policysets', to='policy.PolicySet')),
            ],
            options={
                'verbose_name': '策略集下发',
                'verbose_name_plural': '策略集下发',
                'db_table': 'policyset_send_down',
                'ordering': ('created_time',),
            },
        ),
        migrations.AddField(
            model_name='policyset',
            name='policys',
            field=models.ManyToManyField(through='policy.PolicySetRelation', to='policy.Policy'),
        ),
    ]
