# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-05 15:11
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_auto_20190428_1037'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='policy',
            name='type',
        ),
    ]
