# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-11 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import policy.models


class Migration(migrations.Migration):

    dependencies = [
        ('policy', '0002_auto_20190611_1449'),
    ]

    operations = [
        migrations.AlterField(
            model_name='policy',
            name='creator',
            field=models.ForeignKey(blank=True, db_column='creator', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_policys', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='policy',
            name='item',
            field=policy.models.ListField(default=[], verbose_name='策略项'),
        ),
        migrations.AlterField(
            model_name='policyset',
            name='creator',
            field=models.ForeignKey(blank=True, db_column='creator', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_policysets', to=settings.AUTH_USER_MODEL, verbose_name='创建人'),
        ),
        migrations.AlterField(
            model_name='policyset',
            name='memo',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='policyset',
            name='name',
            field=models.CharField(max_length=255, verbose_name='策略集名称'),
        ),
        migrations.AlterField(
            model_name='policysetrelation',
            name='execute_date',
            field=models.DateField(verbose_name='执行时间'),
        ),
        migrations.AlterField(
            model_name='policysetrelation',
            name='policy',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policy_relations', to='policy.Policy', verbose_name='策略编号'),
        ),
        migrations.AlterField(
            model_name='policysetrelation',
            name='policyset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policyset_relations', to='policy.PolicySet', verbose_name='策略集编号'),
        ),
        migrations.AlterField(
            model_name='policysetsenddown',
            name='hub',
            field=models.ForeignKey(db_column='hub_sn', on_delete=django.db.models.deletion.CASCADE, related_name='hub_send_down_policysets', to='equipment.Hub', verbose_name='集控编号'),
        ),
        migrations.AlterField(
            model_name='policysetsenddown',
            name='policyset',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='policyset_send_down_policysets', to='policy.PolicySet', verbose_name='策略集编号'),
        ),
    ]
