# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-26 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='hub',
            name='new_address',
            field=models.CharField(blank=True, help_text='管控修改过的地址', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='hub',
            name='is_redirect',
            field=models.BooleanField(default=False, help_text='是否重定位', verbose_name='是否重定位'),
        ),
    ]
