# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-20 15:58
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('deleted_time', models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=32, verbose_name='能耗')),
                ('date', models.DateField(verbose_name='日期')),
                ('hub', models.ForeignKey(db_column='hub_sn', on_delete=django.db.models.deletion.CASCADE, related_name='hub_consumption', to='equipment.Hub', verbose_name='集控编号')),
            ],
            options={
                'verbose_name': '集控每日能耗表',
                'verbose_name_plural': '集控每日能耗表',
                'db_table': 'hub_consumption',
            },
        ),
        migrations.CreateModel(
            name='LampCtrlConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('deleted_time', models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('consumption', models.DecimalField(decimal_places=2, max_digits=32, verbose_name='能耗')),
                ('date', models.DateField(verbose_name='日期')),
                ('hub', models.ForeignKey(db_column='hub_sn', on_delete=django.db.models.deletion.CASCADE, related_name='hub_lampctrlconsumption', to='equipment.Hub', verbose_name='集控编号')),
                ('lampctrl', models.ForeignKey(db_column='lampctrl_sn', on_delete=django.db.models.deletion.CASCADE, related_name='lampctrl_consumption', to='equipment.LampCtrl', verbose_name='灯控编号')),
            ],
            options={
                'verbose_name': '路灯每日能耗表',
                'verbose_name_plural': '路灯每日能耗表',
                'db_table': 'lamp_ctrl_consumption',
            },
        ),
    ]
