# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-09 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Consumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('deleted_time', models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('consumption', models.DecimalField(decimal_places=1, help_text='能耗', max_digits=32)),
                ('date', models.DateField(auto_now_add=True, help_text='记录时间')),
                ('hub', models.ForeignKey(help_text='集控编号', on_delete=django.db.models.deletion.CASCADE, related_name='hub_consumption', to='hub.Hub')),
            ],
            options={
                'verbose_name': '集控日能耗',
                'verbose_name_plural': '集控日能耗',
                'db_table': 'consumption',
            },
        ),
        migrations.CreateModel(
            name='TotalPowerConsumption',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('deleted_time', models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('power_consumption', models.DecimalField(decimal_places=1, help_text='总能耗', max_digits=32)),
                ('date', models.DateField(auto_now_add=True, help_text='记录时间')),
            ],
            options={
                'verbose_name': '集控总能耗',
                'verbose_name_plural': '集控总能耗',
                'db_table': 'totalpowerconsumption',
                'ordering': ('date',),
            },
        ),
    ]
