# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-11 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hubconsumption',
            name='consumption',
            field=models.DecimalField(decimal_places=2, max_digits=32, verbose_name='能耗'),
        ),
        migrations.AlterField(
            model_name='hubconsumption',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='hubconsumption',
            name='hub',
            field=models.ForeignKey(db_column='hub_sn', on_delete=django.db.models.deletion.CASCADE, related_name='hub_consumption', to='equipment.Hub', verbose_name='集控编号'),
        ),
        migrations.AlterField(
            model_name='lampctrlconsumption',
            name='consumption',
            field=models.DecimalField(decimal_places=2, max_digits=32, verbose_name='能耗'),
        ),
        migrations.AlterField(
            model_name='lampctrlconsumption',
            name='date',
            field=models.DateField(verbose_name='日期'),
        ),
        migrations.AlterField(
            model_name='lampctrlconsumption',
            name='hub',
            field=models.ForeignKey(db_column='hub_sn', on_delete=django.db.models.deletion.CASCADE, related_name='hub_lampctrlconsumption', to='equipment.Hub', verbose_name='集控编号'),
        ),
        migrations.AlterField(
            model_name='lampctrlconsumption',
            name='lampctrl',
            field=models.ForeignKey(db_column='lampctrl_sn', on_delete=django.db.models.deletion.CASCADE, related_name='lampctrl_consumption', to='equipment.LampCtrl', verbose_name='灯控编号'),
        ),
    ]
