# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-17 16:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('report', '0002_auto_20190412_1746'),
    ]

    operations = [
        migrations.AlterField(
            model_name='dailytotalconsumption',
            name='date',
            field=models.DateField(help_text='日期'),
        ),
        migrations.AlterField(
            model_name='hubdailytotalconsumption',
            name='date',
            field=models.DateField(help_text='日期'),
        ),
    ]
