# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-29 09:31
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('base', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('deleted_time', models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('sn', models.CharField(help_text='编号', max_length=32)),
                ('vendor', models.CharField(help_text='厂家名称', max_length=32)),
                ('model', models.CharField(help_text='型号', max_length=32)),
                ('length', models.FloatField(help_text='长度')),
                ('date', models.DateField(help_text='购买时间')),
                ('address', models.CharField(blank=True, help_text='安装地址', max_length=255, null=True)),
                ('memo', models.CharField(blank=True, help_text='备注', max_length=255, null=True)),
            ],
            options={
                'verbose_name': '电缆',
                'verbose_name_plural': '电缆',
                'db_table': 'cable',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='CBox',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('deleted_time', models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('sn', models.CharField(help_text='编号', max_length=32)),
                ('vendor', models.CharField(help_text='厂家名称', max_length=32)),
                ('model', models.CharField(help_text='型号', max_length=32)),
                ('date', models.DateField(help_text='购买时间')),
                ('longitude', models.FloatField(help_text='经度')),
                ('latitude', models.FloatField(help_text='纬度')),
                ('address', models.CharField(blank=True, help_text='安装地址', max_length=255, null=True)),
                ('memo', models.CharField(blank=True, help_text='备注', max_length=255, null=True)),
                ('is_used', models.BooleanField(default=False, help_text='是否已用')),
            ],
            options={
                'verbose_name': '控制箱',
                'verbose_name_plural': '控制箱',
                'db_table': 'cbox',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='CBoxImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('deleted_time', models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('file', models.ImageField(upload_to='asset/cbox/', verbose_name='控制箱图片')),
            ],
            options={
                'verbose_name': '控制箱图片',
                'verbose_name_plural': '控制箱图片',
                'db_table': 'cbox_image',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Hub',
            fields=[
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('deleted_time', models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('sn', models.CharField(help_text='编号', max_length=16, primary_key=True, serialize=False, verbose_name='编号')),
                ('status', models.IntegerField(choices=[(1, '正常'), (2, '故障'), (3, '脱网')], help_text='状态', verbose_name='状态')),
                ('rf_band', models.IntegerField(help_text='信道', verbose_name='信道')),
                ('rf_addr', models.IntegerField(help_text='通讯模块逻辑地址', verbose_name='通讯模块逻辑地址')),
                ('address', models.CharField(help_text='地址', max_length=60, verbose_name='地址')),
                ('new_address', models.CharField(blank=True, help_text='管控修改过的地址', max_length=255, null=True)),
                ('longitude', models.FloatField(help_text='经度', max_length=8, verbose_name='经度')),
                ('latitude', models.FloatField(help_text='纬度', max_length=8, verbose_name='纬度')),
                ('memo', models.CharField(blank=True, help_text='备注', max_length=255, null=True, verbose_name='备注')),
                ('registered_time', models.DateField(help_text='注册时间', verbose_name='注册时间')),
                ('is_redirect', models.BooleanField(default=False, help_text='是否重定位', verbose_name='是否重定位')),
                ('version', models.CharField(help_text='集控版本号', max_length=16, verbose_name='集控版本号')),
            ],
            options={
                'verbose_name': '集控',
                'verbose_name_plural': '集控',
                'db_table': 'hub',
                'ordering': ('registered_time',),
            },
        ),
        migrations.CreateModel(
            name='Lamp',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('deleted_time', models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('sn', models.CharField(help_text='编号', max_length=32)),
                ('vendor', models.CharField(help_text='厂家名称', max_length=32)),
                ('model', models.CharField(help_text='型号', max_length=32)),
                ('date', models.DateField(help_text='购买时间')),
                ('address', models.CharField(blank=True, help_text='安装地址', max_length=255, null=True)),
                ('memo', models.CharField(blank=True, help_text='备注', max_length=255, null=True)),
                ('is_used', models.BooleanField(default=False, help_text='是否已用')),
            ],
            options={
                'verbose_name': '灯具',
                'verbose_name_plural': '灯具',
                'db_table': 'lamp',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='LampCtrl',
            fields=[
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('deleted_time', models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('sn', models.CharField(help_text='灯控编号', max_length=16, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField(help_text='序列号')),
                ('status', models.SmallIntegerField(choices=[(1, '正常'), (2, '故障'), (3, '脱网')], default=1, help_text='灯控状态(正常/故障/脱网)')),
                ('switch_status', models.SmallIntegerField(choices=[(0, '关'), (1, '开')], default=0, help_text='灯控状态(开关)')),
                ('lamp_type', models.SmallIntegerField(choices=[(1, '单路钠灯'), (2, '单路LED灯'), (3, '双路钠灯'), (4, '双路LED灯'), (5, '线路开关')], default=1, help_text='灯具类型')),
                ('is_repeated', models.BooleanField(default=False, help_text='是否是中继')),
                ('rf_band', models.IntegerField(help_text='信道')),
                ('rf_addr', models.IntegerField(help_text='通讯模块逻辑地址')),
                ('address', models.CharField(help_text='集控配置地址', max_length=60)),
                ('new_address', models.CharField(blank=True, help_text='管控修改过的地址', max_length=255, null=True)),
                ('longitude', models.FloatField(help_text='经度', max_length=8)),
                ('latitude', models.FloatField(help_text='纬度', max_length=8)),
                ('on_map', models.BooleanField(default=False, help_text='是否在地图上显示')),
                ('memo', models.CharField(blank=True, help_text='备注', max_length=255, null=True)),
                ('version', models.CharField(blank=True, help_text='固件版本', max_length=255, null=True, verbose_name='固件版本')),
                ('registered_time', models.DateField(default=datetime.datetime.now, help_text='入网时间')),
                ('is_redirect', models.BooleanField(default=False, help_text='是否重定位', verbose_name='是否重定位')),
                ('hub', models.ForeignKey(help_text='集控编号', on_delete=django.db.models.deletion.CASCADE, related_name='hub_lampctrl', to='equipment.Hub')),
            ],
            options={
                'verbose_name': '灯控',
                'verbose_name_plural': '灯控',
                'db_table': 'lampctrl',
                'ordering': ('hub', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='LampImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('deleted_time', models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('file', models.ImageField(upload_to='asset/lamp/', verbose_name='灯具图片')),
            ],
            options={
                'verbose_name': '灯具图片',
                'verbose_name_plural': '灯具图片',
                'db_table': 'lamp_image',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('deleted_time', models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('sn', models.CharField(help_text='编号', max_length=32)),
                ('vendor', models.CharField(help_text='厂家名称', max_length=32)),
                ('model', models.CharField(help_text='型号', max_length=32)),
                ('height', models.FloatField(help_text='高度')),
                ('date', models.DateField(help_text='购买时间')),
                ('longitude', models.FloatField(help_text='经度')),
                ('latitude', models.FloatField(help_text='纬度')),
                ('address', models.CharField(blank=True, help_text='安装地址', max_length=255, null=True)),
                ('memo', models.CharField(blank=True, help_text='备注', max_length=255, null=True)),
                ('is_used', models.BooleanField(default=False, help_text='是否已用')),
            ],
            options={
                'verbose_name': '灯杆',
                'verbose_name_plural': '灯杆',
                'db_table': 'pole',
                'ordering': ['-created_time'],
            },
        ),
        migrations.CreateModel(
            name='PoleImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('deleted_time', models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('file', models.ImageField(upload_to='asset/pole/', verbose_name='灯杆图片')),
            ],
            options={
                'verbose_name': '灯杆图片',
                'verbose_name_plural': '灯杆图片',
                'db_table': 'pole_image',
                'ordering': ['-created_time'],
            },
        ),
        migrations.AddField(
            model_name='pole',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.PoleImage'),
        ),
        migrations.AddField(
            model_name='lamp',
            name='bearer',
            field=models.ForeignKey(help_text='灯杆编号', on_delete=django.db.models.deletion.CASCADE, related_name='pole_lamp', to='equipment.Pole'),
        ),
        migrations.AddField(
            model_name='lamp',
            name='controller',
            field=models.ForeignKey(help_text='灯控编号', on_delete=django.db.models.deletion.CASCADE, related_name='lampctrl_lamp', to='equipment.LampCtrl'),
        ),
        migrations.AddField(
            model_name='lamp',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.LampImage'),
        ),
        migrations.AddField(
            model_name='hub',
            name='pole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pole_hub', to='equipment.Pole', verbose_name='灯杆'),
        ),
        migrations.AddField(
            model_name='hub',
            name='unit',
            field=models.ForeignKey(blank=True, help_text='管理单元', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='unit_hub', to='base.Unit', verbose_name='管理单元'),
        ),
        migrations.AddField(
            model_name='cbox',
            name='image',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='equipment.CBoxImage'),
        ),
        migrations.AlterUniqueTogether(
            name='lampctrl',
            unique_together=set([('hub', 'sequence')]),
        ),
    ]
