# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-11 17:11
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='pole',
            field=models.ForeignKey(blank=True, db_column='pole_id', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pole_hub', to='equipment.Pole', verbose_name='灯杆'),
        ),
        migrations.AlterField(
            model_name='lamp',
            name='bearer',
            field=models.ForeignKey(db_column='bearer', help_text='灯杆编号', on_delete=django.db.models.deletion.CASCADE, related_name='pole_lamp', to='equipment.Pole'),
        ),
        migrations.AlterField(
            model_name='pole',
            name='sn',
            field=models.CharField(help_text='编号', max_length=32),
        ),
    ]
