# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-10 11:52
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='hub',
            name='pole',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='pole_hub', to='equipment.Pole', verbose_name='灯杆'),
        ),
    ]
