# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-11 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='permission',
            name='hub',
            field=models.ForeignKey(db_column='hub_sn', on_delete=django.db.models.deletion.CASCADE, related_name='hub_permision', to='equipment.Hub', verbose_name='集控编号'),
        ),
        migrations.AlterField(
            model_name='permission',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_permission', to=settings.AUTH_USER_MODEL, verbose_name='用户编号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_read_only',
            field=models.BooleanField(default=False, verbose_name='是否只读用户'),
        ),
        migrations.AlterField(
            model_name='user',
            name='is_receive_alarm',
            field=models.BooleanField(default=False, verbose_name='是否接收告警'),
        ),
        migrations.AlterField(
            model_name='user',
            name='updated_user',
            field=models.ForeignKey(blank=True, db_column='updated_user', null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='修改者'),
        ),
        migrations.AlterField(
            model_name='user',
            name='user_group',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='users', to='user.UserGroup', verbose_name='用户组编号'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(max_length=32, verbose_name='用户名'),
        ),
        migrations.AlterModelTable(
            name='usergroup',
            table='user_group',
        ),
    ]
