# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-23 11:05
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0002_auto_20190423_1031'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='read_only_user',
            new_name='is_read_only',
        ),
        migrations.RenameField(
            model_name='user',
            old_name='receive_alarm',
            new_name='is_receive_alarm',
        ),
    ]
