# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-28 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lamp', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Cable',
            fields=[
                ('sn', models.CharField(db_index=True, help_text='编号', max_length=32, primary_key=True, serialize=False)),
                ('vendor', models.CharField(help_text='厂家名称', max_length=32)),
                ('model', models.CharField(help_text='型号', max_length=32)),
                ('length', models.FloatField(help_text='长度')),
                ('date', models.DateField(help_text='购买时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('address', models.CharField(blank=True, help_text='安装地址', max_length=32, null=True)),
                ('memo', models.CharField(blank=True, help_text='备注', max_length=64, null=True)),
            ],
            options={
                'db_table': 'cable',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='CBox',
            fields=[
                ('sn', models.CharField(db_index=True, help_text='编号', max_length=32, primary_key=True, serialize=False)),
                ('vendor', models.CharField(help_text='厂家名称', max_length=32)),
                ('model', models.CharField(help_text='型号', max_length=32)),
                ('date', models.DateField(help_text='购买时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('longitude', models.FloatField(help_text='经度')),
                ('latitude', models.FloatField(help_text='纬度')),
                ('address', models.CharField(blank=True, help_text='安装地址', max_length=32, null=True)),
                ('memo', models.CharField(blank=True, help_text='备注', max_length=64, null=True)),
                ('is_used', models.BooleanField(default=False, help_text='是否已用')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='asset/cbox/')),
            ],
            options={
                'db_table': 'cbox',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Lamp',
            fields=[
                ('sn', models.CharField(db_index=True, help_text='编号', max_length=32, primary_key=True, serialize=False)),
                ('vendor', models.CharField(help_text='厂家名称', max_length=32)),
                ('model', models.CharField(help_text='型号', max_length=32)),
                ('date', models.DateField(help_text='购买时间')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('address', models.CharField(blank=True, help_text='安装地址', max_length=32, null=True)),
                ('memo', models.CharField(blank=True, help_text='备注', max_length=64, null=True)),
                ('is_used', models.BooleanField(default=False, help_text='是否已用')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='asset/lamp/')),
            ],
            options={
                'db_table': 'lamp',
                'ordering': ['-created_at'],
            },
        ),
        migrations.CreateModel(
            name='Pole',
            fields=[
                ('sn', models.CharField(db_index=True, help_text='编号', max_length=32, primary_key=True, serialize=False)),
                ('vendor', models.CharField(help_text='厂家名称', max_length=32)),
                ('model', models.CharField(help_text='型号', max_length=32)),
                ('height', models.FloatField(help_text='高度')),
                ('date', models.DateField(help_text='购买时间')),
                ('longitude', models.FloatField(help_text='经度')),
                ('latitude', models.FloatField(help_text='纬度')),
                ('created_at', models.DateTimeField(auto_now_add=True, help_text='创建时间')),
                ('address', models.CharField(blank=True, help_text='安装地址', max_length=32, null=True)),
                ('memo', models.CharField(blank=True, help_text='备注', max_length=64, null=True)),
                ('is_used', models.BooleanField(default=False, help_text='是否已用')),
                ('image', models.ImageField(blank=True, default=None, null=True, upload_to='asset/pole/')),
            ],
            options={
                'db_table': 'pole',
                'ordering': ['-created_at'],
            },
        ),
        migrations.AddField(
            model_name='lamp',
            name='bearer',
            field=models.ForeignKey(help_text='灯杆编号', on_delete=django.db.models.deletion.CASCADE, related_name='pole_lamp', to='asset.Pole'),
        ),
        migrations.AddField(
            model_name='lamp',
            name='controller',
            field=models.ForeignKey(help_text='灯控编号', on_delete=django.db.models.deletion.CASCADE, related_name='lampctrl_lamp', to='lamp.LampCtrl'),
        ),
    ]
