# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-18 11:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('asset', '0002_auto_20190418_1136'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cable',
            name='address',
            field=models.CharField(blank=True, help_text='安装地址', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cable',
            name='memo',
            field=models.CharField(blank=True, help_text='备注', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cbox',
            name='address',
            field=models.CharField(blank=True, help_text='安装地址', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='cbox',
            name='memo',
            field=models.CharField(blank=True, help_text='备注', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lamp',
            name='address',
            field=models.CharField(blank=True, help_text='安装地址', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='lamp',
            name='memo',
            field=models.CharField(blank=True, help_text='备注', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pole',
            name='address',
            field=models.CharField(blank=True, help_text='安装地址', max_length=255, null=True),
        ),
        migrations.AlterField(
            model_name='pole',
            name='memo',
            field=models.CharField(blank=True, help_text='备注', max_length=255, null=True),
        ),
    ]
