# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-04 18:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LampCtrlGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('deleted_time', models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('group_num', models.IntegerField(help_text='分组编号')),
                ('memo', models.CharField(help_text='备注', max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='是否为默认分组')),
                ('hub', models.ForeignKey(help_text='集控编号', on_delete=django.db.models.deletion.CASCADE, related_name='hub_group', to='equipment.Hub')),
                ('lampctrl', models.ForeignKey(help_text='灯控编号', on_delete=django.db.models.deletion.CASCADE, related_name='lampctrl_group', to='equipment.LampCtrl')),
            ],
            options={
                'verbose_name': '灯控分组',
                'verbose_name_plural': '灯控分组',
                'db_table': 'lampctrl_group',
                'ordering': ('hub_id', 'lampctrl_id'),
            },
        ),
    ]
