# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-16 16:37
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='HubLatestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('deleted_time', models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('A_voltage', models.DecimalField(decimal_places=1, default=0, help_text='A相电压', max_digits=32)),
                ('A_current', models.DecimalField(decimal_places=1, default=0, help_text='A相电流', max_digits=32)),
                ('A_power', models.DecimalField(decimal_places=1, default=0, help_text='A相功率', max_digits=32)),
                ('A_consumption', models.DecimalField(decimal_places=1, default=0, help_text='A相能耗', max_digits=32)),
                ('B_voltage', models.DecimalField(decimal_places=1, default=0, help_text='B相电压', max_digits=32)),
                ('B_current', models.DecimalField(decimal_places=1, default=0, help_text='B相电流', max_digits=32)),
                ('B_power', models.DecimalField(decimal_places=1, default=0, help_text='B相功率', max_digits=32)),
                ('B_consumption', models.DecimalField(decimal_places=1, default=0, help_text='B相能耗', max_digits=32)),
                ('C_voltage', models.DecimalField(decimal_places=1, default=0, help_text='C相电压', max_digits=32)),
                ('C_current', models.DecimalField(decimal_places=1, default=0, help_text='C相电流', max_digits=32)),
                ('C_power', models.DecimalField(decimal_places=1, default=0, help_text='C相功率', max_digits=32)),
                ('C_consumption', models.DecimalField(decimal_places=1, default=0, help_text='C相能耗', max_digits=32)),
                ('voltage', models.DecimalField(decimal_places=1, default=0, help_text='总电压', max_digits=32)),
                ('current', models.DecimalField(decimal_places=1, default=0, help_text='总电流', max_digits=32)),
                ('power', models.DecimalField(decimal_places=1, default=0, help_text='总功率', max_digits=32)),
                ('consumption', models.DecimalField(decimal_places=1, default=0, help_text='总能耗', max_digits=32)),
                ('time', models.DateTimeField(auto_now_add=True)),
                ('sn', models.ForeignKey(help_text='集控编号', on_delete=django.db.models.deletion.CASCADE, related_name='hub_latest_status', to='equipment.Hub')),
            ],
            options={
                'verbose_name': '集控最新状态',
                'verbose_name_plural': '集控最新状态',
                'db_table': 'hub_latest_status',
                'ordering': ('-updated_time',),
            },
        ),
        migrations.CreateModel(
            name='HubStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('deleted_time', models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('A_voltage', models.DecimalField(decimal_places=1, default=0, help_text='A相电压', max_digits=32)),
                ('A_current', models.DecimalField(decimal_places=1, default=0, help_text='A相电流', max_digits=32)),
                ('A_power', models.DecimalField(decimal_places=1, default=0, help_text='A相功率', max_digits=32)),
                ('A_consumption', models.DecimalField(decimal_places=1, default=0, help_text='A相能耗', max_digits=32)),
                ('B_voltage', models.DecimalField(decimal_places=1, default=0, help_text='B相电压', max_digits=32)),
                ('B_current', models.DecimalField(decimal_places=1, default=0, help_text='B相电流', max_digits=32)),
                ('B_power', models.DecimalField(decimal_places=1, default=0, help_text='B相功率', max_digits=32)),
                ('B_consumption', models.DecimalField(decimal_places=1, default=0, help_text='B相能耗', max_digits=32)),
                ('C_voltage', models.DecimalField(decimal_places=1, default=0, help_text='C相电压', max_digits=32)),
                ('C_current', models.DecimalField(decimal_places=1, default=0, help_text='C相电流', max_digits=32)),
                ('C_power', models.DecimalField(decimal_places=1, default=0, help_text='C相功率', max_digits=32)),
                ('C_consumption', models.DecimalField(decimal_places=1, default=0, help_text='C相能耗', max_digits=32)),
                ('voltage', models.DecimalField(decimal_places=1, default=0, help_text='总电压', max_digits=32)),
                ('current', models.DecimalField(decimal_places=1, default=0, help_text='总电流', max_digits=32)),
                ('power', models.DecimalField(decimal_places=1, default=0, help_text='总功率', max_digits=32)),
                ('consumption', models.DecimalField(decimal_places=1, default=0, help_text='总能耗', max_digits=32)),
                ('sn', models.ForeignKey(help_text='集控编号', on_delete=django.db.models.deletion.CASCADE, related_name='hub_status', to='equipment.Hub')),
            ],
            options={
                'verbose_name': '集控状态历史',
                'verbose_name_plural': '集控状态历史',
                'db_table': 'hub_status',
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='LampCtrlLatestStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('deleted_time', models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('route_one', models.IntegerField(blank=True, null=True)),
                ('route_two', models.IntegerField(blank=True, null=True)),
                ('voltage', models.DecimalField(decimal_places=1, help_text='电压', max_digits=32)),
                ('current', models.DecimalField(decimal_places=1, help_text='电流', max_digits=32)),
                ('power', models.DecimalField(decimal_places=1, help_text='功率', max_digits=32)),
                ('consumption', models.DecimalField(decimal_places=1, help_text='能耗', max_digits=32)),
                ('lampctrl', models.OneToOneField(help_text='灯控编号', on_delete=django.db.models.deletion.CASCADE, related_name='lampctrl_latest_status', to='equipment.LampCtrl')),
            ],
            options={
                'verbose_name': '灯控最新状态',
                'verbose_name_plural': '灯控最新状态',
                'db_table': 'lampctrl_latest_status',
                'ordering': ('-updated_time',),
            },
        ),
        migrations.CreateModel(
            name='LampCtrlStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('deleted_time', models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('route_one', models.IntegerField(blank=True, null=True)),
                ('route_two', models.IntegerField(blank=True, null=True)),
                ('voltage', models.DecimalField(decimal_places=1, help_text='电压', max_digits=32)),
                ('current', models.DecimalField(decimal_places=1, help_text='电流', max_digits=32)),
                ('power', models.DecimalField(decimal_places=1, help_text='功率', max_digits=32)),
                ('consumption', models.DecimalField(decimal_places=1, help_text='能耗', max_digits=32)),
                ('lampctrl', models.ForeignKey(help_text='灯控编号', on_delete=django.db.models.deletion.CASCADE, related_name='lampctrl_status', to='equipment.LampCtrl')),
            ],
            options={
                'verbose_name': '灯控状态历史',
                'verbose_name_plural': '灯控状态历史',
                'db_table': 'lampctrl_status',
                'ordering': ('-created_time',),
            },
        ),
    ]
