# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-11 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampctrllateststatus',
            name='lampctrl',
            field=models.OneToOneField(db_column='lampctrl_sn', help_text='灯控编号', on_delete=django.db.models.deletion.CASCADE, related_name='lampctrl_latest_status', to='equipment.LampCtrl'),
        ),
        migrations.AlterField(
            model_name='lampctrlstatus',
            name='lampctrl',
            field=models.ForeignKey(db_column='lampctrl_sn', help_text='灯控编号', on_delete=django.db.models.deletion.CASCADE, related_name='lampctrl_status', to='equipment.LampCtrl'),
        ),
        migrations.AlterField(
            model_name='lampctrlstatus',
            name='route_one',
            field=models.IntegerField(blank=True, help_text='亮度1', null=True),
        ),
        migrations.AlterField(
            model_name='lampctrlstatus',
            name='route_two',
            field=models.IntegerField(blank=True, help_text='亮度2', null=True),
        ),
    ]
