# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-16 18:26
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('status', '0002_auto_20190516_1822'),
    ]

    operations = [
        migrations.RenameField(
            model_name='hublateststatus',
            old_name='sn',
            new_name='hub',
        ),
        migrations.RenameField(
            model_name='hubstatus',
            old_name='sn',
            new_name='hub',
        ),
    ]
