# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-28 16:33
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Setting',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('option', models.CharField(max_length=255, unique=True)),
                ('option_zhcn', models.CharField(max_length=255)),
                ('value', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '系统设置',
                'verbose_name_plural': '系统设置',
                'db_table': 'setting',
                'ordering': ('id',),
            },
        ),
        migrations.CreateModel(
            name='SettingType',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('name_zhcn', models.CharField(max_length=255)),
            ],
            options={
                'verbose_name': '系统设置分类',
                'verbose_name_plural': '系统设置分类',
                'db_table': 'setting_type',
            },
        ),
        migrations.AddField(
            model_name='setting',
            name='s_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='setting.SettingType'),
        ),
    ]
