# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-11 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='setting.SettingType', verbose_name='设置类型'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='value',
            field=models.CharField(max_length=255, verbose_name='值'),
        ),
        migrations.AlterField(
            model_name='settingtype',
            name='name',
            field=models.CharField(max_length=255, verbose_name='设置类型名(显示)'),
        ),
    ]
