# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-11 16:26
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_auto_20190611_1610'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='type',
            field=models.ForeignKey(db_column='type', on_delete=django.db.models.deletion.CASCADE, related_name='settings', to='setting.SettingType', verbose_name='设置类型'),
        ),
    ]
