# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-17 10:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('setting', '0002_setting_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='setting',
            name='name',
            field=models.CharField(max_length=255, verbose_name='设置名(显示)'),
        ),
        migrations.AlterField(
            model_name='setting',
            name='option',
            field=models.CharField(max_length=255, unique=True, verbose_name='设置名'),
        ),
    ]
