# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-09 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hub', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='LampCtrl',
            fields=[
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('deleted_time', models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('sn', models.CharField(help_text='灯控编号', max_length=16, primary_key=True, serialize=False)),
                ('sequence', models.IntegerField(help_text='序列号')),
                ('status', models.SmallIntegerField(choices=[(1, '正常'), (2, '故障'), (3, '脱网')], default=1, help_text='灯控状态(正常/故障/脱网)')),
                ('switch_status', models.SmallIntegerField(choices=[(0, '关'), (1, '开')], default=0, help_text='灯控状态(开关)')),
                ('lamp_type', models.SmallIntegerField(choices=[(1, '单路钠灯'), (2, '单路LED灯'), (3, '双路钠灯'), (4, '双路LED灯')], default=1, help_text='灯具类型')),
                ('is_repeated', models.BooleanField(default=False, help_text='是否是中继')),
                ('rf_band', models.IntegerField(help_text='信道')),
                ('rf_addr', models.IntegerField(help_text='通讯模块逻辑地址')),
                ('address', models.CharField(help_text='集控配置地址', max_length=60)),
                ('new_address', models.CharField(blank=True, help_text='管控修改过的地址', max_length=255, null=True)),
                ('longitude', models.FloatField(help_text='经度', max_length=8)),
                ('latitude', models.FloatField(help_text='纬度', max_length=8)),
                ('on_map', models.BooleanField(default=False, help_text='是否在地图上显示')),
                ('memo', models.CharField(blank=True, help_text='备注', max_length=255, null=True)),
                ('failure_date', models.DateField(blank=True, help_text='故障日期', null=True)),
                ('registered_time', models.DateField(default=django.utils.timezone.now, help_text='入网时间')),
                ('hub', models.ForeignKey(help_text='集控编号', on_delete=django.db.models.deletion.CASCADE, related_name='hub_lampctrl', to='hub.Hub')),
            ],
            options={
                'verbose_name': '灯控',
                'verbose_name_plural': '灯控',
                'db_table': 'lampctrl',
                'ordering': ('hub', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='LampCtrlGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('deleted_time', models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('group_num', models.IntegerField(help_text='分组编号')),
                ('memo', models.CharField(help_text='备注', max_length=255, null=True)),
                ('is_default', models.BooleanField(default=False, help_text='是否为默认分组')),
                ('hub', models.ForeignKey(help_text='集控编号', on_delete=django.db.models.deletion.CASCADE, related_name='hub_group', to='hub.Hub')),
                ('lampctrl', models.ForeignKey(help_text='灯控编号', on_delete=django.db.models.deletion.CASCADE, related_name='lampctrl_group', to='lamp.LampCtrl')),
            ],
            options={
                'verbose_name': '灯控分组',
                'verbose_name_plural': '灯控分组',
                'db_table': 'lampctrl_group',
                'ordering': ('hub_id', 'lampctrl_id'),
            },
        ),
        migrations.CreateModel(
            name='LampCtrlStatus',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('deleted_time', models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('voltage', models.DecimalField(decimal_places=1, help_text='电压', max_digits=32)),
                ('current', models.DecimalField(decimal_places=1, help_text='电流', max_digits=32)),
                ('power', models.DecimalField(decimal_places=1, help_text='功率', max_digits=32)),
                ('power_consumption', models.DecimalField(decimal_places=1, help_text='能耗', max_digits=32)),
                ('time', models.DateTimeField(auto_now_add=True, help_text='上报时间')),
                ('lampctrl', models.ForeignKey(help_text='灯控编号', on_delete=django.db.models.deletion.CASCADE, related_name='lampctrl_status', to='lamp.LampCtrl')),
            ],
            options={
                'verbose_name': '灯控状态历史',
                'verbose_name_plural': '灯控状态历史',
                'db_table': 'lampstatus',
                'ordering': ('time',),
            },
        ),
        migrations.AlterUniqueTogether(
            name='lampctrl',
            unique_together=set([('hub', 'sequence')]),
        ),
    ]
