# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-18 17:40
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamp', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='lampctrl',
            name='lamp_type',
            field=models.SmallIntegerField(choices=[(1, '单路钠灯'), (2, '单路LED灯'), (3, '双路钠灯'), (4, '双路LED灯'), (5, '线路开关')], default=1, help_text='灯具类型'),
        ),
    ]
