# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-26 15:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('lamp', '0002_auto_20190418_1740'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='lampctrl',
            name='failure_date',
        ),
        migrations.AddField(
            model_name='lampctrl',
            name='is_redirect',
            field=models.BooleanField(default=False, help_text='是否重定位', verbose_name='是否重定位'),
        ),
        migrations.AddField(
            model_name='lampctrlstatus',
            name='route_one',
            field=models.IntegerField(null=True),
        ),
        migrations.AddField(
            model_name='lampctrlstatus',
            name='route_two',
            field=models.IntegerField(null=True),
        ),
    ]
