# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-13 08:47
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='公司名称', max_length=16)),
                ('city', models.CharField(help_text='城市名称', max_length=16)),
                ('longitude', models.FloatField(help_text='经度', max_length=8)),
                ('latitude', models.FloatField(help_text='纬度', max_length=8)),
                ('zoom_level', models.IntegerField(default=17, help_text='缩放级别')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
                'db_table': 'projectinfo',
                'ordering': ('id',),
            },
        ),
    ]
