# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-11 14:49
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='ProjectInfo',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('deleted_time', models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('name', models.CharField(help_text='公司名称', max_length=16)),
                ('city', models.CharField(help_text='城市名称', max_length=16)),
                ('longitude', models.FloatField(help_text='经度', max_length=8)),
                ('latitude', models.FloatField(help_text='纬度', max_length=8)),
                ('zoom_level', models.IntegerField(default=17, help_text='缩放级别')),
            ],
            options={
                'verbose_name': '项目信息',
                'verbose_name_plural': '项目信息',
                'db_table': 'projectinfo',
                'ordering': ('id',),
            },
        ),
    ]
