# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-03-13 09:44
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('projectinfo', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='projectinfo',
            name='created_time',
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now, help_text='创建时间', verbose_name='创建时间'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='deleted_time',
            field=models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True, verbose_name='删除时间'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='is_deleted',
            field=models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除'),
        ),
        migrations.AddField(
            model_name='projectinfo',
            name='updated_time',
            field=models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间'),
        ),
    ]
