# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-04 18:20
from __future__ import unicode_literals

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('equipment', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Alert',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('deleted_time', models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('event', models.CharField(help_text='告警事件', max_length=64)),
                ('level', models.SmallIntegerField(choices=[(1, '告警'), (2, '故障'), (3, '严重故障')], help_text='故障级别')),
                ('object_type', models.CharField(choices=[('hub', '集控'), ('lamp', '灯控')], help_text='告警设备类型', max_length=16)),
                ('object', models.CharField(help_text='产生告警的设备(集控/灯控)', max_length=64)),
                ('memo', models.CharField(blank=True, help_text='备注', max_length=255, null=True)),
                ('occurred_time', models.DateTimeField(default=datetime.datetime.now)),
                ('is_solved', models.BooleanField(default=False, help_text='是否解决')),
                ('solved_time', models.DateTimeField(auto_now=True, help_text='处理时间', null=True)),
                ('alert_source', models.ForeignKey(db_column='alert_source', help_text='告警源(集控)', on_delete=django.db.models.deletion.CASCADE, related_name='hub_alert', to='equipment.Hub')),
            ],
            options={
                'verbose_name': '告警',
                'verbose_name_plural': '告警',
                'db_table': 'alert',
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='AlertAudio',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('deleted_time', models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('audio', models.FileField(upload_to='audio', verbose_name='告警语音')),
                ('times', models.IntegerField(default=0)),
                ('alert', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_audio', to='notify.Alert')),
            ],
            options={
                'verbose_name': '告警语音',
                'verbose_name_plural': '告警语音',
                'db_table': 'alert_audio',
                'ordering': ('-id',),
            },
        ),
        migrations.CreateModel(
            name='Log',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_deleted', models.BooleanField(default=False, help_text='是否删除', verbose_name='是否删除')),
                ('created_time', models.DateTimeField(auto_now_add=True, help_text='创建时间', verbose_name='创建时间')),
                ('updated_time', models.DateTimeField(auto_now=True, help_text='更新时间', null=True, verbose_name='更新时间')),
                ('deleted_time', models.DateTimeField(blank=True, db_index=True, help_text='删除时间', null=True, verbose_name='删除时间')),
                ('username', models.CharField(help_text='操作人员用户名', max_length=64)),
                ('event', models.CharField(help_text='操作事件', max_length=1024)),
                ('object', models.CharField(help_text='操作对象', max_length=255)),
                ('status', models.IntegerField(choices=[(0, 'success'), (1, 'fail')], verbose_name='操作状态')),
                ('memo', models.CharField(blank=True, help_text='详情', max_length=1024, null=True)),
            ],
            options={
                'verbose_name': '日志',
                'verbose_name_plural': '日志',
                'db_table': 'log',
                'ordering': ('-created_time',),
            },
        ),
    ]
