# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-28 16:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('hub', '0001_initial'),
        ('notify', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.AddField(
            model_name='log',
            name='user',
            field=models.ForeignKey(help_text='操作人员用户名', on_delete=django.db.models.deletion.CASCADE, related_name='user_log', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='alert',
            name='alert_source',
            field=models.ForeignKey(help_text='告警源(集控)', on_delete=django.db.models.deletion.CASCADE, related_name='hub_alert', to='hub.Hub'),
        ),
        migrations.AddField(
            model_name='alert',
            name='solver',
            field=models.ForeignKey(blank=True, help_text='处理人员', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='solved_alert', to=settings.AUTH_USER_MODEL),
        ),
    ]
