# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-04 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_alert_solver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaudio',
            name='alert',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_audio', to='notify.Alert'),
        ),
    ]
