# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-11 16:10
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_alert_solver'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alertaudio',
            name='alert',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='alert_audio', to='notify.Alert', verbose_name='告警编号'),
        ),
        migrations.AlterField(
            model_name='alertaudio',
            name='times',
            field=models.IntegerField(default=0, verbose_name='被听次数'),
        ),
    ]
