# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-05-17 10:46
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0002_auto_20190516_1637'),
    ]

    operations = [
        migrations.AddField(
            model_name='alert',
            name='occurred_time',
            field=models.DateTimeField(default=datetime.datetime.now),
        ),
    ]
