# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-26 18:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('notify', '0005_auto_20190417_1411'),
    ]

    operations = [
        migrations.AlterField(
            model_name='alert',
            name='alert_source',
            field=models.ForeignKey(db_column='alert_source', help_text='告警源(集控)', on_delete=django.db.models.deletion.CASCADE, related_name='hub_alert', to='hub.Hub'),
        ),
    ]
