# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-02-28 16:33
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('lamp', '0001_initial'),
        ('hub', '0001_initial'),
        ('notify', '0001_initial'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Inspection',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('memo', models.CharField(max_length=1023, null=True)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_inspetion', to='hub.Hub')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inspection', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'inspection',
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='InspectionImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='inspection')),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('inspection', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_image', to='workorder.Inspection')),
            ],
            options={
                'db_table': 'inspectionimage',
            },
        ),
        migrations.CreateModel(
            name='InspectionItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('sequence', models.IntegerField()),
                ('status', models.IntegerField(choices=[(1, '正常'), (2, '故障')])),
                ('memo', models.CharField(blank=True, max_length=1023, null=True)),
                ('inspection_id', models.IntegerField()),
                ('hub', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hub_inspection_item', to='hub.Hub')),
                ('lamp', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='lampctrl_inspection_item', to='lamp.LampCtrl')),
            ],
            options={
                'db_table': 'inspectionitem',
                'ordering': ('hub', 'sequence'),
            },
        ),
        migrations.CreateModel(
            name='WorkOrder',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('w_type', models.IntegerField(choices=[(1, '集控'), (2, '灯杆'), (3, '灯具'), (4, '电缆'), (5, '控制箱'), (6, '其它')], help_text='工单类型')),
                ('obj_sn', models.CharField(blank=True, max_length=32, null=True)),
                ('sequence', models.IntegerField(blank=True, null=True)),
                ('message', models.CharField(blank=True, max_length=255, null=True)),
                ('status', models.CharField(choices=[('todo', '未处理'), ('doing', '处理中'), ('finished', '已处理')], default='todo', max_length=16)),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('finished_time', models.DateTimeField(default=None, null=True)),
                ('memo', models.CharField(blank=True, max_length=255, null=True)),
                ('alert', models.ForeignKey(blank=True, help_text='告警编号', null=True, on_delete=django.db.models.deletion.CASCADE, related_name='alert_workorder', to='notify.Alert')),
                ('lampctrl', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='lampctrl_workorder', to='lamp.LampCtrl')),
                ('user', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='user_workorder', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'db_table': 'workorder',
                'ordering': ('-created_time',),
            },
        ),
        migrations.CreateModel(
            name='WorkorderImage',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('image', models.ImageField(upload_to='workorder')),
                ('image_type', models.IntegerField(choices=[(0, '无'), (1, '维修问题描述图片'), (2, '工单处理图片')])),
                ('created_time', models.DateTimeField(auto_now_add=True)),
                ('order', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorder_image', to='workorder.WorkOrder')),
            ],
            options={
                'db_table': 'workorderimage',
            },
        ),
    ]
