# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-11 16:10
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='inspection',
            name='hub',
            field=models.ForeignKey(db_column='hub_sn', on_delete=django.db.models.deletion.CASCADE, related_name='hub_inspetion', to='equipment.Hub', verbose_name='集控编号'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='memo',
            field=models.CharField(max_length=1023, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='inspection',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='user_inspection', to=settings.AUTH_USER_MODEL, verbose_name='巡检人'),
        ),
        migrations.AlterField(
            model_name='inspectionimage',
            name='file',
            field=models.ImageField(upload_to='inspection', verbose_name='巡检图片'),
        ),
        migrations.AlterField(
            model_name='inspectionimage',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_image', to='workorder.Inspection', verbose_name='巡检编号'),
        ),
        migrations.AlterField(
            model_name='inspectionitem',
            name='hub',
            field=models.ForeignKey(db_column='hub_sn', on_delete=django.db.models.deletion.CASCADE, related_name='hub_inspection_item', to='equipment.Hub', verbose_name='集控编号'),
        ),
        migrations.AlterField(
            model_name='inspectionitem',
            name='inspection',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='inspection_item', to='workorder.Inspection', verbose_name='巡检编号'),
        ),
        migrations.AlterField(
            model_name='inspectionitem',
            name='lampctrl',
            field=models.ForeignKey(db_column='lampctrl_sn', on_delete=django.db.models.deletion.CASCADE, related_name='lampctrl_inspection_item', to='equipment.LampCtrl', verbose_name='灯控编号'),
        ),
        migrations.AlterField(
            model_name='inspectionitem',
            name='memo',
            field=models.CharField(blank=True, max_length=1023, null=True, verbose_name='备注'),
        ),
        migrations.AlterField(
            model_name='inspectionitem',
            name='status',
            field=models.IntegerField(choices=[(1, '正常'), (2, '故障')], verbose_name='状态'),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='finished_time',
            field=models.DateTimeField(blank=True, help_text='完成时间', null=True),
        ),
        migrations.AlterField(
            model_name='workorder',
            name='status',
            field=models.CharField(choices=[('todo', '未处理'), ('doing', '处理中'), ('finished', '已处理')], default='todo', max_length=16, verbose_name='工单状态'),
        ),
        migrations.AlterField(
            model_name='workorderaudio',
            name='order',
            field=models.OneToOneField(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='workorder_audio', to='workorder.WorkOrder', verbose_name='工单编号'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='workorderaudio',
            name='times',
            field=models.IntegerField(default=0, verbose_name='被听次数'),
        ),
        migrations.AlterField(
            model_name='workorderimage',
            name='file',
            field=models.ImageField(upload_to='workorder', verbose_name='工单图片'),
        ),
        migrations.AlterField(
            model_name='workorderimage',
            name='image_type',
            field=models.IntegerField(choices=[(0, '无'), (1, '维修问题描述图片'), (2, '工单处理图片')], default=0, verbose_name='工单类型'),
        ),
        migrations.AlterField(
            model_name='workorderimage',
            name='order',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='workorder_image', to='workorder.WorkOrder', verbose_name='工单编号'),
        ),
        migrations.AlterModelTable(
            name='inspectionimage',
            table='inspection_image',
        ),
        migrations.AlterModelTable(
            name='inspectionitem',
            table='inspection_item',
        ),
        migrations.AlterModelTable(
            name='workorderimage',
            table='workorder_image',
        ),
    ]
