# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-13 15:00
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='workorder',
            name='lampctrl',
        ),
        migrations.RemoveField(
            model_name='workorder',
            name='sequence',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='type',
            field=models.IntegerField(choices=[(0, '其它'), (1, '集控'), (2, '灯杆'), (3, '灯具'), (4, '电缆'), (5, '控制箱')], help_text='工单类型'),
        ),
    ]
