# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-04 19:40
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorderaudio',
            name='order',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='workorder_audio', to='workorder.WorkOrder'),
        ),
    ]
