# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-17 09:59
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0002_auto_20190413_1500'),
    ]

    operations = [
        migrations.AlterField(
            model_name='workorder',
            name='type',
            field=models.IntegerField(choices=[(0, '其它'), (1, '集控'), (2, '灯控'), (3, '灯杆'), (4, '灯具'), (5, '电缆'), (6, '控制箱')], help_text='工单类型'),
        ),
    ]
