# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-06-20 11:20
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0002_auto_20190611_1610'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='inspectionitem',
            options={'ordering': ('lampctrl',), 'verbose_name': '巡检具体项', 'verbose_name_plural': '巡检具体项'},
        ),
        migrations.RemoveField(
            model_name='inspectionitem',
            name='hub',
        ),
    ]
