# -*- coding: utf-8 -*-
# Generated by Django 1.11.6 on 2019-04-18 15:56
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('workorder', '0004_auto_20190418_1048'),
    ]

    operations = [
        migrations.RenameField(
            model_name='inspectionimage',
            old_name='image',
            new_name='file',
        ),
        migrations.RenameField(
            model_name='workorderimage',
            old_name='image',
            new_name='file',
        ),
        migrations.AlterField(
            model_name='workorder',
            name='memo',
            field=models.CharField(max_length=255, verbose_name='备注'),
        ),
    ]
